# Generated by Django 3.2.23 on 2024-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('studio', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('winner', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
